# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import modules.landing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_creado', models.DateTimeField(auto_now=True)),
                ('categorias', models.CharField(choices=[('DP', 'Deportes'), ('VJ', 'Video Juegos'), ('AM', 'Animales'), ('MD', 'Moda'), ('AT', 'Autos'), ('OT', 'Otros')], max_length=50)),
                ('imagen', models.ImageField(upload_to=modules.landing.models.user_directory_path)),
            ],
        ),
    ]
